### ISSUE TITLE
Only IPv6 nodes are not handled

### ISSUE THREAD

**Issue by M5oul** [duniter/silkaj#14]
```bash
2a01:e35:8ae7:8bb0:7b0a:b4ec:ad04:dd57
Traceback (most recent call last):
  File "./silkaj", line 50, in <module>
    manage_cmd(ep, c)
  File "./silkaj", line 25, in manage_cmd
    network_info(ep, c.contains_switches("discover"))
  File "/home/moul/projects/silkaj/src/commands.py", line 67, in network_info
    endpoints = discover_peers(ep, discover)
  File "/home/moul/projects/silkaj/src/network_tools.py", line 18, in discover_peers
    if best_node(ep, 0) is None: endpoints.remove(ep)
  File "/home/moul/projects/silkaj/src/network_tools.py", line 101, in best_node
    s.connect((ep[address], port))
socket.gaierror: [Errno -9] Address family for hostname not supported
```

- It [seems it doesn't works as it's a local IP6 address](https://stackoverflow.com/questions/30790075/ipv6-python-sockets-not-working/30790206#30790206)
- Remote nodes with only IP6 are not here: may be as there are not know by non IPv6 nodes.
- [Socket documentation](https://docs.python.org/3/library/socket.html)

**Comment by M5oul** [comment]
May be fixed using an other HTTP lib as `aiohttp` with [Duniter-python-api usage](https://github.com/duniter/silkaj/issues/7).
