### ISSUE TITLE
Bug with `network` command

### ISSUE THREAD

**Issue by c-geek** [duniter/silkaj#2]
Here is the stacktrace:

```
exit
Traceback (most recent call last):
  File "./src/silkaj.py", line 54, in <module>
    manage_cmd(ep, c)
  File "./src/silkaj.py", line 29, in manage_cmd
    if int(columns) >= 146: network_info(ep, int(columns))
  File "/home/cgeek/dev/silkaj/src/commands.py", line 67, in network_info
    current_blk = get_current_block(endpoints[i])
  File "/home/cgeek/dev/silkaj/src/tools.py", line 21, in get_current_block
    return (request(ep, "blockchain/current"))
  File "/home/cgeek/dev/silkaj/src/network_tools.py", line 60, in request
    url = "http://" + ep[best_node(ep, 0)] + ":" + ep["port"] + "/" + path
KeyError: None
```

**Comment by c-geek** [comment]
Note: it was the second time I used the command. The first time it worked without problem.

**Comment by M5oul** [comment]
Yep, there is a bug when there is at least one node not accessible, my code exit.
I will have to refactor that part.

**Comment by M5oul** [comment]
Ok, I pushed a temporal fix:
- if a node do not answer, do not quit the program.
- optional peer are currently no more checked.

**Comment by M5oul** [comment]
Ok, previous workaround wasn't working.
I found a solution.
