### ISSUE TITLE
network command fails

### ISSUE THREAD

**Issue by jellium** [duniter/silkaj#51]
This might be related to other issues ([opened](https://github.com/duniter/silkaj/issues/32) or [closed](https://github.com/duniter/silkaj/issues/2)) related to `network` command (not likely I believe).

Using `silkaj network` returns:

```
Requested default node: <duniter.org:10901>
Getting informations about nodes:
0% g1.cgeek.fr 80
3% g1.duniter.org 10901
7% g1.duniter.tednet.fr 8999
10% duniter-g1.vincentux.fr 443
13% g1.smyds.net 80
17% wotex.cgeek.fr 63700
20% remuniter.cgeek.fr 16120
23% g1.elois.org 80
27% g2.elois.org 10901
30% g1-monit.elois.org 10901
33% g1.monnaielibreoccitanie.org 443
37% duniter.help-web-low.fr 8999
40% g1.sl-network.fr 443
43% duniter.silibre.com 80
47% 88.162.208.159 25250
50% duniter.polyno.me 10901
53% 82.239.120.237 28128
57% 86.67.130.26 57500
60% 88.162.208.159 34479
63% 151.80.155.53 8999
67% g1.duniter.fr 10901
70% duniter.youpeek.net 80
Traceback (most recent call last):
  File "/opt/silkaj/0.3.0/silkaj", line 116, in <module>
    manage_cmd(ep, c)
  File "/opt/silkaj/0.3.0/silkaj", line 91, in manage_cmd
    network_info(ep, c.contains_switches("discover"))
  File "/opt/silkaj/0.3.0/src/commands.py", line 139, in network_info
    current_blk = get_current_block(endpoints[i])
  File "/opt/silkaj/0.3.0/src/tools.py", line 44, in get_current_block
    return request(ep, "blockchain/current")
  File "/opt/silkaj/0.3.0/src/network_tools.py", line 112, in request
    return json.loads(response.read().decode(encoding))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Whereas using `silkaj network --discover` returns:

```
Requested default node: <duniter.org:10901>
Discovering network
0%
3%
6%
9%
12%
Traceback (most recent call last):
  File "/opt/silkaj/0.3.0/silkaj", line 116, in <module>
    manage_cmd(ep, c)
  File "/opt/silkaj/0.3.0/silkaj", line 91, in manage_cmd
    network_info(ep, c.contains_switches("discover"))
  File "/opt/silkaj/0.3.0/src/commands.py", line 109, in network_info
    endpoints = [OrderedDict((i, p.get(i, None)) for i in ("domain", "port", "ip4", "ip6", "pubkey")) for p in discover_peers(ep, discover)]
  File "/opt/silkaj/0.3.0/src/network_tools.py", line 25, in discover_peers
    endpoints = recursive_discovering(endpoints, ep)
  File "/opt/silkaj/0.3.0/src/network_tools.py", line 34, in recursive_discovering
    news = parse_endpoints(request(ep, "network/peers")["peers"])
  File "/opt/silkaj/0.3.0/src/network_tools.py", line 110, in request
    response = urllib.request.urlopen(request)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

Thanks for this cool cli client anyway!

**Comment by M5oul** [comment]
Thanks for the bug report.
In fact I already noticed this bug many times.
I think the best solution is to use duniter-python-api which check Json format and don't get stucked with 404 errors.
